mode: development # Use "hyde publish -c prod.yaml to have this automatically switch to production
media_root: media # Relative path from content folder.
media_url: /media # URL where the media files are served from.
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.meta.AutoExtendPlugin
    - hyde.ext.plugins.meta.SorterPlugin
    - hyde.ext.plugins.meta.GrouperPlugin
    - hyde.ext.plugins.urls.UrlCleanerPlugin
    - hyde.ext.plugins.text.TextlinksPlugin

context:
    data:
        site_title: C.Y.
        author:
            name: Charles Yuan
            url: "http://www.beta4better.me"
        google_analytics_id: UA-9439246-12
        home_url: /
        menu:
            - title: Home
              url: /
            - title: About
              url: /about

sorter:
    latest:
        attr: meta.date
        reverse: True
